<?php
require_once __DIR__ . '/../shared_session_bootstrap.php';

/*
 * Legacy standalone No-Show handler.
 * Kept separate from the UI, but must enforce the same booking rules and
 * role-scoped service access as admin/managebooking.php.
 */

$current_role_raw = strtolower(trim((string)($_SESSION['role'] ?? '')));
$role_aliases = [
    'administrator' => 'admin',
    'shop manager' => 'manager',
    'shop_manager' => 'manager',
    'front desk' => 'receptionist',
    'front desk / receptionist' => 'receptionist',
    'front_desk' => 'receptionist',
    'front_desk_receptionist' => 'receptionist',
    'grooming staff' => 'groomer',
    'grooming_staff' => 'groomer',
    'grooming staff / groomer' => 'groomer',
    'grooming_staff_groomer' => 'groomer',
    'pet hotel staff' => 'pet_hotel_staff',
    'pet hotel staff / attendant' => 'pet_hotel_staff',
    'pet_hotel_attendant' => 'pet_hotel_staff',
    'pet_hotel_staff_attendant' => 'pet_hotel_staff',
    'staff' => 'groomer',
    'supervisor' => 'receptionist',
];
$current_role = $role_aliases[$current_role_raw] ?? $current_role_raw;
$allowed_roles = ['admin', 'manager', 'receptionist', 'groomer', 'pet_hotel_staff'];
$is_logged_in = ($_SESSION['logged_in'] ?? false) === true;

if (!$is_logged_in || !in_array($current_role, $allowed_roles, true)) {
    http_response_code(403);
    exit('Unauthorized access.');
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    exit('Method not allowed.');
}

// A session CSRF token is generated by the booking-management page.
$session_token = (string)($_SESSION['csrf_token'] ?? '');
$posted_token = (string)($_POST['csrf_token'] ?? '');
if ($session_token === '' || $posted_token === '' || !hash_equals($session_token, $posted_token)) {
    http_response_code(403);
    exit('Invalid or expired request token. Refresh the page and try again.');
}

$appointment_id = filter_var($_POST['appointment_id'] ?? null, FILTER_VALIDATE_INT);
$user_id = filter_var($_POST['user_id'] ?? null, FILTER_VALIDATE_INT);
if (!$appointment_id || !$user_id || $appointment_id < 1 || $user_id < 1) {
    http_response_code(400);
    exit('Invalid appointment_id or user_id.');
}

function noShowServiceAllowedForRole(string $role, string $service): bool
{
    $service = strtolower(trim($service));

    if ($role === 'groomer') {
        return str_starts_with($service, 'grooming');
    }
    if ($role === 'pet_hotel_staff') {
        return str_starts_with($service, 'pet hotel');
    }

    return in_array($role, ['admin', 'manager', 'receptionist'], true);
}

require_once __DIR__ . '/../db_supabase.php';

try {
    $pdo->beginTransaction();

    // Lock the appointment and validate its owner, service and state.
    $check_appointment = $pdo->prepare("
        SELECT id, user_id, booking_status, reschedule_count, service
        FROM appointments
        WHERE id = :appointment_id
        LIMIT 1
        FOR UPDATE
    ");
    $check_appointment->execute([':appointment_id' => $appointment_id]);
    $appointment = $check_appointment->fetch(PDO::FETCH_ASSOC);

    if (!$appointment) {
        throw new DomainException('Appointment not found.', 404);
    }

    if ((int)($appointment['user_id'] ?? 0) !== $user_id) {
        throw new DomainException('Appointment does not belong to this user.', 403);
    }

    if (!noShowServiceAllowedForRole($current_role, (string)($appointment['service'] ?? ''))) {
        throw new DomainException('Access denied for this service booking.', 403);
    }

    $status_now = strtoupper(trim((string)($appointment['booking_status'] ?? '')));
    $reschedule_count = (int)($appointment['reschedule_count'] ?? 0);

    if ($status_now === 'NO-SHOW') {
        throw new DomainException('This appointment is already marked as No-Show.', 409);
    }

    // Match the booking manager's rule: No-Show is final only after the
    // customer's one-time reschedule has been used.
    if ($status_now !== 'RESCHEDULED' || $reschedule_count !== 1) {
        throw new DomainException(
            "No-Show is only available after the customer's one-time reschedule has been used.",
            409
        );
    }

    // Lock the customer record before incrementing strikes.
    $check_user = $pdo->prepare("
        SELECT id, no_show_count, is_restricted
        FROM users
        WHERE id = :user_id
        LIMIT 1
        FOR UPDATE
    ");
    $check_user->execute([':user_id' => $user_id]);
    $user = $check_user->fetch(PDO::FETCH_ASSOC);

    if (!$user) {
        throw new DomainException('User account not found.', 404);
    }

    $new_strike_count = max(0, (int)($user['no_show_count'] ?? 0)) + 1;
    $is_restricted = $new_strike_count >= 3;

    // Use a guarded update as a second line of defense against race conditions.
    $update_appointment = $pdo->prepare("
        UPDATE appointments
        SET booking_status = 'No-Show'
        WHERE id = :appointment_id
          AND user_id = :user_id
          AND UPPER(COALESCE(booking_status, '')) = 'RESCHEDULED'
          AND COALESCE(reschedule_count, 0) = 1
    ");
    $update_appointment->execute([
        ':appointment_id' => $appointment_id,
        ':user_id' => $user_id,
    ]);

    if ($update_appointment->rowCount() !== 1) {
        throw new DomainException('Appointment status was not updated. Refresh and try again.', 409);
    }

    $update_user = $pdo->prepare("
        UPDATE users
        SET no_show_count = :no_show_count,
            is_restricted = :is_restricted
        WHERE id = :user_id
    ");
    $update_user->execute([
        ':no_show_count' => $new_strike_count,
        ':is_restricted' => $is_restricted,
        ':user_id' => $user_id,
    ]);

    $pdo->commit();

    if ($is_restricted) {
        echo 'Marked as No-Show successfully. User has reached 3 strikes and is now restricted.';
    } else {
        echo "Marked as No-Show successfully. Strike count: {$new_strike_count}.";
    }
} catch (DomainException $e) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }
    $status_code = (int)$e->getCode();
    http_response_code($status_code >= 400 && $status_code < 500 ? $status_code : 400);
    echo $e->getMessage();
} catch (PDOException $e) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }
    error_log('Mark No-Show database error: ' . $e->getMessage());
    http_response_code(500);
    echo 'Failed to mark appointment as No-Show.';
} catch (Throwable $e) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }
    error_log('Mark No-Show unexpected error: ' . $e->getMessage());
    http_response_code(500);
    echo 'Failed to mark appointment as No-Show.';
}
