<?php
require_once __DIR__ . '/../shared_session_bootstrap.php';
require_once '../db_supabase.php';

// Security: this endpoint is restricted to authenticated Admin accounts.
$current_role = strtolower(trim((string)($_SESSION['role'] ?? '')));
if (
    !isset($_SESSION['logged_in']) ||
    $_SESSION['logged_in'] !== true ||
    $current_role !== 'admin'
) {
    header('Location: ../admin_login.php');
    exit();
}

// Deletion must only be performed using POST.
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    exit('Method not allowed.');
}

// Verify the session-bound CSRF token generated by managepromo.php.
$session_token = $_SESSION['csrf_token'] ?? '';
$submitted_token = $_POST['csrf_token'] ?? '';
if (
    !is_string($session_token) ||
    $session_token === '' ||
    !is_string($submitted_token) ||
    !hash_equals($session_token, $submitted_token)
) {
    http_response_code(403);
    exit('Invalid security token.');
}

// Validate the promo ID submitted by the management form.
$promo_id = filter_input(INPUT_POST, 'id', FILTER_VALIDATE_INT);
if ($promo_id === false || $promo_id === null || $promo_id <= 0) {
    header('Location: managepromo.php');
    exit();
}

try {
    $pdo->beginTransaction();

    // Lock and retrieve the row so its image path is known before deletion.
    $find_stmt = $pdo->prepare(
        'SELECT id, image_url FROM promos WHERE id = :promo_id LIMIT 1 FOR UPDATE'
    );
    $find_stmt->execute([':promo_id' => $promo_id]);
    $promo = $find_stmt->fetch(PDO::FETCH_ASSOC);

    if (!$promo) {
        $pdo->rollBack();
        header('Location: managepromo.php');
        exit();
    }

    $delete_stmt = $pdo->prepare('DELETE FROM promos WHERE id = :promo_id');
    $delete_stmt->execute([':promo_id' => $promo_id]);

    if ($delete_stmt->rowCount() !== 1) {
        throw new RuntimeException('Promotion could not be deleted.');
    }

    // Commit the database operation before attempting file cleanup.
    $pdo->commit();

    // Only remove generated promo images stored inside uploads/promos.
    $image_url = (string)($promo['image_url'] ?? '');
    if (
        $image_url !== '' &&
        preg_match('#^/?uploads/promos/([A-Za-z0-9._-]+\.(?:jpg|jpeg|png|webp))$#i', $image_url, $matches)
    ) {
        $project_root = dirname(__DIR__);
        $upload_dir = realpath(
            $project_root . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'promos'
        );

        if ($upload_dir !== false) {
            $candidate = $upload_dir . DIRECTORY_SEPARATOR . $matches[1];
            $real_image_path = realpath($candidate);

            if (
                $real_image_path !== false &&
                is_file($real_image_path) &&
                dirname($real_image_path) === $upload_dir
            ) {
                // A cleanup failure should not undo the already-committed DB deletion.
                if (!@unlink($real_image_path)) {
                    error_log('Delete promo: unable to remove associated image file for promo ID ' . $promo_id);
                }
            }
        }
    }
} catch (Throwable $e) {
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }

    error_log('Delete promo error: ' . $e->getMessage());
}

header('Location: managepromo.php');
exit();
